zenangst/Tailor

- Pod/Podfile.lock
- Source/Tailor.swift
Added two type alias
```swift
public typealias JSONArray = [[String : AnyObject]]
public typealias JSONDictionary = [String : AnyObject]
```
Now you no longer need to have `[String : AnyObject]` floating around in your code.
> Add type alias for JSON payloads

- Pod/Podfile.lock
- Pod/Tests/TestMappable.swift
- Pod/Tests/TestSubjects.swift
- Source/Tailor.swift
You can now map object relations, this is the first iteration so I think it can improve a lot in terms of the public API, but it works :sunglasses:
```swift
relatives <- map.relation("relatives") { (objects: [[String : AnyObject]]?) -> [TestPersonStruct]? in
guard let objects = objects else { return self.relatives }
for object in objects { self.relatives.append(TestPersonStruct(object)) }
return self.relatives
}
```
```swift
let testStruct = TestPersonStruct([
"firstName" : "Taylor",
"lastName" : "Swift",
"sex": "female",
"birth_date": "2014-07-15",
"relatives" : [
["firstName" : "Mini",
"lastName" : "Swift",
"sex": "female",
"birth_date": "2014-07-17"],
["firstName" : "Mini-Mini",
"lastName" : "Swift",
"sex": "female",
"birth_date": "2014-07-17"]
]
])
```
> Add relation mapping and improve public API

- Pod/Pod.xcodeproj/project.pbxproj
- Pod/Podfile.lock
- Pod/Tests/TestInspectable.swift
- Source/Tailor.swift
You can now find nested attributes with the following syntax.
```swift 
object.property("relatives.0")
```
```swift
let data: [String : AnyObject] = ["firstName" : "Taylor",
"lastName" : "Swift",
"sex": "female",
"birth_date": "2014-07-15"]
var parent = TestPersonStruct(data)
var clone = parent
clone.firstName += " + Clone"
parent.relatives.append(clone)
XCTAssertEqual(parent.property("relatives.0"), clone)
```
> Initial implementation of inspectable nested attributes

- Pod/Tests/TestMappable.swift
- Pod/Tests/TestSubjects.swift
- Source/Tailor.swift
- Tailor.podspec
Mapping relations should be a whole lot simpler now.
```swift
relatives <- map.relation("relatives") { (objects: JSONArray?) -> [TestPersonStruct]? in
guard let objects = objects else { return self.relatives }
for object in objects { self.relatives.append(TestPersonStruct(object)) }
return self.relatives
```
```swift
relatives <- map.relation("relatives")
```
> Refactor relation mapping

- Pod/Tests/TestMappable.swift
- Pod/Tests/TestSubjects.swift
- Source/Tailor.swift
This pull request introduces a new method; `.object(name: String)`.
It simply maps a `Mappable` object with a dictionary.
From here on end, we have the following method to use when mapping JSON to an object;
```swift
string <- map.property("string")
```
```swift
object <- map.object(["key" : "value"])
```
```swift
relations <- map.relation([["key" : "value"]])
```
> Feature new object mapping.

- Pod/Podfile.lock
- Pod/Tests/TestSubjects.swift
- Source/Tailor.swift
- Tailor.podspec
Instead of using `.relation`, we will do `.objects`.
> Rename relation to objects

- Pod/Tests/TestMappable.swift
- Pod/Tests/TestSubjects.swift
- Source/Tailor.swift
Tailor can now append object and objects to property lists that are declared as `let`.
```swift
testStruct.relatives <+ relatives.object("first")
```
```swift
testStruct.relatives <+ relatives.objects()
```
> Feature <+ infix operator

- .travis.yml
- Cartfile.resolved
- Playground-Mac.playground/Contents.swift
- Sources/Shared/Tailor.swift
- Tailor.xcodeproj/project.pbxproj
- Tailor.xcodeproj/xcshareddata/xcschemes/Tailor-Mac.xcscheme
- Tailor.xcodeproj/xcshareddata/xcschemes/Tailor-iOS.xcscheme
- TailorTests/Shared/TestMappable.swift
This PR adds a new method on `Inspectable` objects.
It can be used to safely get values via key from any object that conforms to the `Inspectable` protocol.
```swift
do {
let firstName: String = try taylor.value("firstName")
let lastName: String? = try taylor.value("lastName")
let age: Int = try taylor.value("age")
} catch { print(error) }
```
```swift
public func value<T>(key: String) throws -> T {
let value = Mirror(reflecting: self)
.children
.filter { $0.label == key }
.map { $1 }.first
guard let objectValue = value as? T else {
throw MappableError.TypeError(message: "Tried to get value \(value!) for \(key) as \(T.self) when expecting \(types()[key]!)")
}
return objectValue
}
```
The method `throws` to make sure that you are getting the correct value type back.
As an added bonus, the …
> Improve object lookup

- README.md
- Sources/Shared/Extensions/Dictionary+Tailor.swift
- Sources/Shared/Protocols/Mappable.swift
- TailorTests/Shared/TestMappable.swift
- TailorTests/Shared/TestSubjects.swift
So the last adventure caused some issues which made some of the properties unmappable because it some of the function signatures got mixed up. This PR fixes that issue and renames two of the functions in the public API.
Mapping objects use `relation`, mapping multiple options is done with `relations`.
This also adds one new mapping functions called `directory` which is a dictionary with objects.
> Refactor and revert to old API setup

- Sources/Shared/Extensions/Array+Tailor.swift
- Sources/Shared/Extensions/Dictionary+Tailor.swift
- Tailor.xcodeproj/project.pbxproj
- TailorTests/Shared/TestAccessible.swift
Add some syntactic sugar to access dictionary and array, useful when
- Need to only access some path inside dictionary or array
```swift
if let marvelClubJSON = json.dictionary("school")?.array("clubs")?.dictionary(1) {
let club = Club(marvelClubJSON)
}
```
- When the map JSONDictionary contains unwanted structure
```swift
struct Club {
var people: [Person] = []
init(_ map: JSONDictionary) {
people <- map.dictionary("detail")?.relations("people")
}
}
```
Test added
> Add dictionary and array method to Dictionary and Array

- Cartfile.resolved
- Sources/Shared/Extensions/Array+Tailor.swift
> Support objects for SafeMappable

- Sources/Shared/Protocols/PathAccessible.swift
- Sources/Shared/Tailor.swift
- Tailor.xcodeproj/project.pbxproj
- TailorTests/Shared/TestMappable.swift
So that we can use it like
```swift
self.secret <- map.path(["chaos", 1, "way", "light", 1])?.property("secret")
```
Initially, I want to use variadic parameter instead of array, but it seems to not work with these `LiteralConvertible` https://github.com/onmyway133/issues/issues/133
> Add PathAccessible for easy accessing through path with key and index

- Sources/Shared/Extensions/Dictionary+Tailor.swift
- Sources/Shared/Protocols/HierarchyType.swift
- Tailor.xcodeproj/project.pbxproj
- TailorTests/Shared/TestHierarchyType.swift
There are cases like GitHub API https://github.com/onmyway133/Github.swift/tree/master/Sources/Classes/Event where we want to parse and return corresponding subclasses instead, so this PR supports that 😬
> Hierarchy Type

- Sources/Shared/Extensions/Dictionary+Tailor.swift
- TailorTests/Shared/TestSubjects.swift
- Use as? instead of as!
- Remove unneeded temporary variables
> Remove boilerplate

- Sources/Shared/Operators/Operators.swift
- Sources/Shared/Protocols/DefaultType.swift
- Tailor.xcodeproj/project.pbxproj
- TailorTests/Shared/TestDefaultType.swift
There are cases that users just want `struct` with `let` declaration. Previously, we have to declare `var` for `<-` to work. This just uses simple assignment with default value
- Add DefaultType for type that has default value
- Add `<?` operator to fall back to default value
```swift
struct Book: Mappable {
let name: String
let pageCount: Int
let website: NSURL?
init(_ map: JSONDictionary) {
name = <?map.property("name")
pageCount = <?map.property("page_count")
website = map.transform("website_url", transformer: NSURL.init(string: ))
}
}
```
> Support defaultValue

- TailorTests/Shared/TestAccessible.swift
This adds type information to json in the test. It makes it build faster, and ensures it is of type `JSONDictionary`
This shows an example of the difference in the types
```swift
// Dictionary<String, AnyObject>
let json: [String: AnyObject] = [
"key": "value"
]
// Dictionary<String, NSDictionary>
let json = [
"key": "value"
]
```
This is also because `extension Dictionary: PathAccessible {}`, it would be great if only `JSONDictionary` can conform to `PathAccessible`
> Add type information

- Sources/Shared/Protocols/PathAccessible.swift
- TailorTests/Shared/TestAccessible.swift
This PR aims to improve the usability of resolving key paths.
With this pull request you can resolve nested paths like this;
```swift
XCTAssertEqual(json.path("school.clubs.0.detail.name"), "DC")
XCTAssertEqual(json.path("school.clubs.0.detail.people.0.first_name"), "Clark")
XCTAssertEqual(json.path("school.clubs.0.detail.people.0.age"), 78)
XCTAssertEqual(json.path("school.clubs.0.detail.people")!, [
[
"first_name": "Clark",
"last_name": "Kent",
"age" : 78
],
[
"first_name": "Bruce",
"last_name": "Wayne",
"age" : 77
]
])
```
It can achieve this with the refactoring done in `PathAccessible` to introduce method overloading for the `path` method.
> Improve resolving paths

- TailorTests/Shared/TestAccessible.swift
We have had some small issues with mapping floats since we transitioned to Swift 3. This PR just improves the test coverage.
> Add test for mapping floats

- README.md
- Sources/Shared/Extensions/Dictionary+Tailor.swift
- TailorTests/Shared/DefaultTypesMappingTests.swift
Add method for mapping boolean value from a Dictionary.
> Add support for mapping booleans

- Sources/Shared/Extensions/Dictionary+Tailor.swift
- Sources/Shared/Extensions/Optional+Extensions.swift
- Sources/Shared/Operators/Operators.swift
- Tailor.xcodeproj/project.pbxproj
- TailorTests/Shared/DefaultTypesMappingTests.swift
- TailorTests/Shared/TestAccessible.swift
- TailorTests/Shared/TestDefaultType.swift
- TailorTests/Shared/TestInspectable.swift
- TailorTests/Shared/TestMappable.swift
- TailorTests/Shared/TestSubjects.swift
- Remove all the `orThrow` method. This adds `unwrapOrThrow` on optional. So this is more like `Optional -> Throw`. We now don't need to have 2 methods
- Remove some custom operators. We don't really need these
- Also, re-indent all the test files to use 2 spaces
> Throw using optional
